# Generated by Django 4.2.3 on 2023-08-02 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userbaseinfo',
            table='UserBaseInfo',
        ),
    ]
