# Generated by Django 4.2.3 on 2023-08-03 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_alter_userbaseinfo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userbaseinfo',
            table='UserBaseInfo2',
        ),
    ]
