# Generated by Django 4.2.3 on 2023-08-03 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_alter_userbaseinfo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbaseinfo',
            options={},
        ),
        migrations.AlterModelTable(
            name='userbaseinfo',
            table=None,
        ),
    ]
