# Generated by Django 4.2.3 on 2023-08-03 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_alter_userbaseinfo_options_alter_userbaseinfo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbaseinfo',
            options={'verbose_name': '人员基本信息'},
        ),
        migrations.AlterModelTable(
            name='userbaseinfo',
            table='UserBaseInfo2',
        ),
    ]
