# Generated by Django 4.2.3 on 2023-08-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_alter_userbaseinfo_options_alter_userbaseinfo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userbaseinfo',
            table='UserBaseInfo',
        ),
    ]
